"""user management: username, email verification, password reset

Revision ID: 11773bec62e1
Revises: 6231ce012268
Create Date: 2026-08-17 21:43:31.620828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11773bec62e1'
down_revision = '6231ce012268'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-adjusted from the autogenerated version: rename 'name' ->
    # 'username' in place (autogenerate saw this as drop+add, which would
    # have discarded every existing user's display name). Existing accounts
    # predate email verification, so they're backfilled as already verified
    # rather than being locked out of a flow that didn't exist when they
    # signed up.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'name', new_column_name='username', existing_type=sa.String(length=120),
            type_=sa.String(length=30),
        )
        batch_op.add_column(
            sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('pending_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('code_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('code_purpose', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('code_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('code_attempts', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('code_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # Match the normalization the app applies to every username going
    # forward (see _normalize_username in app/routes/auth.py).
    op.execute('UPDATE "user" SET username = lower(username)')

    # Defaults above exist only to backfill pre-existing rows; the app
    # always sets these columns explicitly on insert, so drop the defaults
    # to avoid masking a future bug that forgets to.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)
        batch_op.alter_column('code_attempts', server_default=None)


def downgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('code_sent_at')
        batch_op.drop_column('code_attempts')
        batch_op.drop_column('code_expires_at')
        batch_op.drop_column('code_purpose')
        batch_op.drop_column('code_hash')
        batch_op.drop_column('pending_email')
        batch_op.drop_column('email_verified')
        batch_op.alter_column(
            'username', new_column_name='name', existing_type=sa.String(length=30),
            type_=sa.String(length=120),
        )
