"""kombimodul: allow single source module, add graded flag

Revision ID: 333e79dc555b
Revises: 11773bec62e1
Create Date: 2026-08-18 12:56:06.292558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333e79dc555b'
down_revision = '11773bec62e1'
branch_labels = None
depends_on = None


def upgrade():
    # server_default backfills existing rows as graded=True, matching their
    # only behavior before this column existed (always averaged); dropped
    # right after since the app always sets this column explicitly on insert.
    with op.batch_alter_table('kombi_modul', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('graded', sa.Boolean(), nullable=False, server_default=sa.true())
        )
    with op.batch_alter_table('kombi_modul', schema=None) as batch_op:
        batch_op.alter_column('graded', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kombi_modul', schema=None) as batch_op:
        batch_op.drop_column('graded')

    # ### end Alembic commands ###
