"""initial schema

Revision ID: 6231ce012268
Revises: 
Create Date: 2026-08-17 16:28:19.214472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6231ce012268'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('modul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modul_user_id'), ['user_id'], unique=False)

    op.create_table('studiengang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_studiengang_user_name')
    )
    with op.batch_alter_table('studiengang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studiengang_user_id'), ['user_id'], unique=False)

    op.create_table('grade_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.CheckConstraint("kind IN ('numeric', 'pass', 'fail')", name='ck_grade_attempt_kind'),
    sa.CheckConstraint('slot >= 1 AND slot <= 3', name='ck_grade_attempt_slot_range'),
    sa.ForeignKeyConstraint(['modul_id'], ['modul.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modul_id', 'slot', name='uq_grade_attempt_modul_slot')
    )
    with op.batch_alter_table('grade_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_attempt_modul_id'), ['modul_id'], unique=False)

    op.create_table('kombi_modul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('studiengang_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['studiengang_id'], ['studiengang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kombi_modul', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kombi_modul_studiengang_id'), ['studiengang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kombi_modul_user_id'), ['user_id'], unique=False)

    op.create_table('modul_studiengang',
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.Column('studiengang_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modul_id'], ['modul.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studiengang_id'], ['studiengang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modul_id', 'studiengang_id')
    )
    op.create_table('submission_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('threshold_percent', sa.Float(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modul_id'], ['modul.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_series_modul_id'), ['modul_id'], unique=False)

    op.create_table('kombimodul_module',
    sa.Column('kombimodul_id', sa.Integer(), nullable=False),
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kombimodul_id'], ['kombi_modul.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modul_id'], ['modul.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kombimodul_id', 'modul_id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('points_achieved', sa.Float(), nullable=False),
    sa.Column('points_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['submission_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'week_number', name='uq_submission_series_week')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_series_id'), ['series_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_series_id'))

    op.drop_table('submission')
    op.drop_table('kombimodul_module')
    with op.batch_alter_table('submission_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_series_modul_id'))

    op.drop_table('submission_series')
    op.drop_table('modul_studiengang')
    with op.batch_alter_table('kombi_modul', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kombi_modul_user_id'))
        batch_op.drop_index(batch_op.f('ix_kombi_modul_studiengang_id'))

    op.drop_table('kombi_modul')
    with op.batch_alter_table('grade_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_attempt_modul_id'))

    op.drop_table('grade_attempt')
    with op.batch_alter_table('studiengang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studiengang_user_id'))

    op.drop_table('studiengang')
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modul_user_id'))

    op.drop_table('modul')
    op.drop_table('user')
    # ### end Alembic commands ###
